fix test

diff --git a/UnitTests/MCPLTests/scripts/testflags b/UnitTests/MCPLTests/scripts/testflags
--- a/UnitTests/MCPLTests/scripts/testflags
+++ b/UnitTests/MCPLTests/scripts/testflags
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 
+set -e
+set -u
+
 #Test all combinations of MCPL_HASZLIB, MCPL_NO_CUSTOM_GZIP and MCPL_NO_EXT_GZIP
 
 #A bit hackish, but we want to compile mcpl again and again:
-#CC=`python -c 'import os; import pickle;print(pickle.load(open(os.path.join(os.getenv("DGCODE_DIR"),".bld/env.cache"),"rb"))["system"]["volatile"]["c"]["compiler"])'`
-CC=`python -c 'import os; import pickle; import dgbuild.cfg as cfg; print(pickle.load(open(cfg.dirs.envcache,"rb"))["system"]["volatile"]["c"]["compiler"])'`
-if [ $? != 0 ]; then
-    exit 1
-fi
 
-CAN_USE_RPATHLINK=$(python -c 'import os; import pickle; import dgbuild.cfg as cfg; print(int(pickle.load(open(cfg.dirs.envcache,"rb"))["system"]["langs"]["c"]["can_use_rpathlink_flag"]))')
+CC=$(python3 -c 'import pickle,dgbuild.cfg as c; print(pickle.loads(c.dirs.envcache.read_bytes())["system"]["langs"]["c"]["compiler"])')
+
+CAN_USE_RPATHLINK=$(python3 -c 'import pickle,dgbuild.cfg as c; print(int(pickle.loads(c.dirs.envcache.read_bytes())["system"]["langs"]["c"].get("can_use_rpathlink_flag",0)))')
 
 P=$DGCODE_DIR/packages/Framework/MCPL/MCPL
 
@@ -24,7 +24,7 @@ if [ x$CAN_USE_RPATHLINK == x1 ]; then
     rpathflags="${rpathflags} -Wl,-rpath-link,$ESS_LIB_DIR -Wl,-rpath-link,$ESS_LIB_DIR/links"
 fi
 
-if [ "x${CONDA_PREFIX}" != x ]; then
+if [ "x${CONDA_PREFIX:-}" != x ]; then
     rpathflags="${rpathflags} -Wl,-rpath,${CONDA_PREFIX}/lib -Wl,-rpath,${CONDA_PREFIX}/lib"
     if [ x$CAN_USE_RPATHLINK == x1 ]; then
         rpathflags="${rpathflags} -Wl,-rpath-link,${CONDA_PREFIX}/lib -Wl,-rpath-link,${CONDA_PREFIX}/lib"
@@ -49,14 +49,21 @@ for a in 0 1; do
             fi
             echo "=========================================================================="
             echo "=== Testing flags: "`echo ${flags}|sed "s#$ESS_INCLUDE_DIR#\\$ESSINC#"`
+            echo "===    rpathflags: ${rpathflags}"
             $CC -std=c99 -lm ${flags} ${rpathflags} -I$ESS_INCLUDE_DIR/MCPL -L$ESS_LIB_DIR/ $P/libsrc/mcpl.c main.c -lm ${flags} ${rpathflags} -o main && ./main
             EC=$?
             ls -1 out.mcpl*
             if [ $? == 0 ]; then
                 echo "=== Again with broken gzip:"
                 rm -f out.mcpl*
-                PATH="$PWD/fakebadgzip:$PATH" ./main
+                failure=0
+                PATH="$PWD/fakebadgzip:$PATH" ./main || failure=1
                 ls -1 out.mcpl*
+                if [ $failure == 1 ]; then
+                    echo "  ==> Exit code non-zero (failure)."
+                else
+                    echo "  ==> Exit code 0."
+                fi
             else
                 echo "compilation failed"
                 exit 1
